name: Build Azure VM Image with Packer

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer
          sudo packer plugins install github.com/hashicorp/azure          
          

      - name: Login to Azure
        run: |
          az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Build image using Packer 2
        run: |
          echo ${{ secrets.AZURE_CLIENT_ID }}
          packer build \
            -var 'client_id=${{ secrets.AZURE_CLIENT_ID }}' \
            -var 'client_secret=${{ secrets.AZURE_CLIENT_SECRET }}' \
            -var 'subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}' \
            -var 'tenant_id=${{ secrets.AZURE_TENANT_ID }}' \
            -var 'build_resource_group_name=1-feb49ddf-playground-sandbox' \
            -var 'build_resource_group_name=1-feb49ddf-playground-sandbox' \
            -var 'shared_image_gallery_destination=demo' \
            ./packer/azure-nginx-template.json
