name: Build Azure VM Image with Packer

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer
          sudo packer plugins install github.com/hashicorp/azure

      - name: Build image using Packer
        run: |
          packer build \
            -var 'client_id=${{ secrets.AZURE_CLIENT_ID }}' \
            -var 'client_secret=${{ secrets.AZURE_CLIENT_SECRET }}' \
            -var 'subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}' \
            -var 'tenant_id=${{ secrets.AZURE_TENANT_ID }}' \
            -var 'resource_group=your-resource-group' \
            ./packer/azure-nginx-template.json
